sudo: required

services:
  - docker

script:
  - docker build -t zokeber/docker-pfn:latest .
  - docker create --privileged -it -p 8181:80 --name php7-fpm-nginx -h php7-fpm-nginx zokeber/docker-pfn
  - docker start php7-fpm-nginx
  - docker stop php7-fpm-nginx
  - docker rm -f php7-fpm-nginx
