---
apiVersion: v1
kind: ReplicationController
metadata:
  name: api
spec:
  replicas: 3
  selector:
    app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      dnsPolicy: ClusterFirst
      containers:
      - name: service
        image: sz-pg-oam-docker-hub-001.tendcloud.com/library/buoyantio-helloworld:0.1.4
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: http_proxy
          value: $(NODE_NAME):4140
        args:
        - "-addr=:7779"
        - "-text=api"
        - "-target=hello"
        - "-json"
        ports:
        - name: service
          containerPort: 7779
      - name: kubectl
        image: sz-pg-oam-docker-hub-001.tendcloud.com/library/buoyantio-kubectl:v1.4.0
        args:
        - proxy
        - "-p"
        - "8001"
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: api
  ports:
  - name: http
    port: 7779
